Only interpolate at non-terminal next states
JuliaPOMDP/LocalApproximationValueIteration.jl pull request #6
Opened 2018-07-12 01:34 UTC by Shushman

In the value iteration and action value functions, a check is made that the `sp` next state is non-terminal before the interpolated value at `sp` is used to update the utility at `s`. This is relevant for settings with terminal actions where the `sp` is a meaningless state constructed by the user to be a terminal state.

2018-07-12 03:37 UTC, zsunberg approved these changes
This looks right to me! glad it was a pretty simple fix.

2018-07-24 00:06 UTC, MaximeBouton commented
When the utility of the terminal state sp is different from 0. there would be an issue no? 

Something should probably be done if the user has set terminal costs via the solver options.

2018-07-24 00:07 UTC, MaximeBouton requested changes
If the utility of the terminal state sp is not 0., it does not get added. Since there is the option to set custom terminal costs this should be probably taken care of. 
or am I missing something?

2018-07-25 17:37 UTC, zsunberg commented
@MaximeBouton are you referring to the `terminal_costs_set` option? I guess I do not understand how this is supposed to work - I thought it had been removed. All rewards and costs should be represented in the MDP definition and the solver should be consistent with this, right? The only things that should be added as solver options are heuristics to help solve the problem.

2018-07-25 17:39 UTC, zsunberg commented
The utility of a terminal state in POMDPs.jl is *always* zero because no actions can be taken and no rewards collected.

2018-07-25 18:11 UTC, MaximeBouton commented
In some problem (e.g. model checking) it can be useful to set it to something different than 1, the value has a different meaning then. It might be too specific though. What was the initial motivation for the terminal cost option?
I think if this option is removed then this implementation would be correct, but if the user is allowed to set the terminal utility to something different than 0, it will not be consistent I think.

2018-07-25 18:26 UTC, Shushman commented
Ah I see. I think the initial motivation for `terminal_costs` was to allow for terminal state utilities, but this came into question recently once another problem came up with categorical variables and unnecessarily adding dimensions to the multi-dimensional grid. Let me think of it carefully and I'll come up with a compromise.

2018-07-25 21:36 UTC, Shushman commented
Sorry @MaximeBouton , I forgot to push my last commit which removes references to `terminal_costs_set`  in the LocalApproximationValueIteration solver entirely, instead making that the responsibility of the MDP's `reward` and `generate_sr` functions.

2018-07-25 22:41 UTC, zsunberg commented
Cool - good catch @MaximeBouton !

2018-07-26 03:09 UTC, MaximeBouton approved these changes

2018-07-26 03:09 UTC, MaximeBouton commented
Looks good!

2018-08-03 06:19 UTC, merged